name: Coverage

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        OS: ubuntu-latest
        PYTHON: '3.9'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.8"
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
            path: .venv
            key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        run: |
            make install-test
      - name: Run Coverage
        run: |
            poetry add coverage codecov
            poetry run coverage run -m pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            verbose: true
