name: Coverage

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        OS: ubuntu-latest
        PYTHON: '3.9'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install Dependencies
        run: |
          make install-test
      - name: Run Coverage
        run: |
            pip install coverage
            coverage run -m pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
