name: Coverage
on:
    push:
      branches: main
    pull_request:
      branches: "*"
jobs:
    test:
      runs-on: ubuntu-latest
      outputs:
        coverage: ${{ steps.coverage.outputs.coverage-report }}
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          id: setup-python
          with:
            python-version: "3.9"
        - uses: snok/install-poetry@v1
          with:
            virtualenvs-create: true
            virtualenvs-in-project: true
            installer-parallel: true
        - name: Load cached venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
              path: .venv
              key: venv-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        - name: Install Dependencies
          if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
          run: |
            make install-test
        - name: Run Coverage
          id: coverage
          run: |
            pip install coverage flake8
            {
                echo 'coverage-report<<EOF'
                make coverage
                echo EOF
            } >> "$GITHUB_OUTPUT"
    comment:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      needs: test
      steps:
        - name: Save output
          run: |
            echo ${{needs.test.outputs.coverage}} > pytest-coverage.txt
        - name: Comment coverage 
          uses: coroo/pytest-coverage-commentator@v1.0.2
          with:
            pytest-coverage: pytest-coverage.txt
